name: gelidonyamr
channels:
  - bioconda
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - flye=2.9
  - multiqc=1.27
  - mlst=2.23.0
  - abricate=1.0.1
  - kraken2=2.1.3
  - chewBBACA=2.8.5
  - fastp=0.24.0
  - nextflow=21.04.1
