FROM mambaorg/micromamba:1.5.8

LABEL maintainer="Gültekin Ünal"
LABEL description="GelidonyAMR — PopPUNK population structure environment"

USER $MAMBA_USER

COPY --chown=$MAMBA_USER:$MAMBA_USER config/envs/poppunk.yaml /tmp/poppunk.yaml

RUN micromamba install -y -n base -f /tmp/poppunk.yaml \
    && micromamba clean --all --yes

ENV PATH="/opt/conda/bin:${PATH}"
