FROM mambaorg/micromamba:1.5.8

LABEL maintainer="Gültekin Ünal"
LABEL description="GelidonyAMR — chewBBACA cgMLST environment"

USER $MAMBA_USER

COPY --chown=$MAMBA_USER:$MAMBA_USER config/envs/cgmlst.yaml /tmp/cgmlst.yaml

RUN micromamba install -y -n base -f /tmp/cgmlst.yaml \
    && micromamba clean --all --yes

ENV PATH="/opt/conda/bin:${PATH}"
